### ISSUE TITLE
link "create club" button to create page

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/release.club#19]
Edit the landing page (here `public/index.html`) to go to the club page. 
This is plain HTML so you can add the URL. 
- - -
This issue is Intentionally tiny to practice the git workflow.
- When the change is committed, push it to GH and open a pull request.
- Now you can go back to main and create a new branch abd start working on the next issue.
- I can review the PR and merge it to the main branch
- This will cause vercel to deploy the merged code to https://release-club.vercel.app/

**Comment by salieflewis** [comment]
appreciate you trying to get me to learn the workflow! I made the change, committed it, a bit hung up on the pull request, so just going to continue locally.

**Comment by neatonk** [comment]
ofc. did you search "github first pull request" yet? If you know how to find and read the docs you need, you can figure anything out... given enough time.
