### ISSUE TITLE
Connect club page to deployed contract

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/release.club#20]
Depends on https://github.com/ReleaseClub/contracts/issues/4 and https://github.com/ReleaseClub/contracts/issues/5.

- add our contracts package to the repo using `npm`.
- import the `ReleaseClub` contract abi from our contracts package (see issue mentioned above).
- use the `clubAddress` passed via the URL to get the list of releases from the club contract
- render up to 20 NFTs followed the "load more" button if there are more to show.
- show up to 20 more NFTs when the "load more" button is clicked.
- repeat until there are no more to display.

**Comment by neatonk** [comment]
For the presentation we can skip the first two lines. The goal for now is to just use the clubAddress to get the NFT contract addresses for display.

**Comment by neatonk** [comment]
@josealonso Did @salieflewis pass this one off to you or is he still working on it?

**Comment by josealonso** [comment]
> @josealonso Did @salieflewis pass this one off to you or is he still working on it?

I didn't ask him. I'm working on it. I forgot to ask. Good catch !!

**Comment by josealonso** [comment]
@salieflewis is on it. Please keep us updated here.

**Comment by neatonk** [comment]
Copied from Discord:

> @salieflewis I think your issue is related to pre-rendering, at least in part... https://nextjs.org/docs/basic-features/pages
> You might also need to tell the NFTPreview component which network you're using, otherwise, it will assume mainnet.

**Comment by neatonk** [comment]
For future reference: https://nextjs.org/docs/advanced-features/automatic-static-optimization

**Comment by neatonk** [comment]
I should be able to complete this issue by using SSR: https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props

**Comment by neatonk** [comment]
Done in staging branch
