### ISSUE TITLE
wirte about smart contract functionality for presentation

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/release.club#27]

**Comment by josealonso** [comment]
Since I can keep on writing the tests until tomorrow, I could explain this if I understood it, @neatonk.

**Comment by neatonk** [comment]
feel free to write your interpretation of the contracts in this issue, unless there's something else you could jump on re funcionality. I'll also write my thoughts soon enough though.

**Comment by neatonk** [comment]
done
