### ISSUE TITLE
Modify the populate page

### ISSUE THREAD

**Issue by josealonso** [ReleaseClub/release.club#37]
Right now the user sees a text input, so he thinks he has to type in something. But he just has to wait until redirection to the *clubaddress* page is done.

**Comment by josealonso** [comment]
I'm going to delete that text input. @dhruv035 and @salieflewis, please elaborate on any other task that has to be done.

**Comment by dhruv035** [comment]
we need the default input removed when you start typing, if you can go further we need another input field, validation checks on both (address and bigint). Then we need to feed the value in the args variable in place of the hardcoded ones.
That should be enough for now.

**Comment by josealonso** [comment]
> we need the default input removed when you start typing, if you can go further we need another input field, validation checks on both (address and bigint). Then we need to feed the value in the args variable in place of the hardcoded ones. That should be enough for now.

Thanks, @dhruv035. I think I understand now.

**Comment by josealonso** [comment]
What are the field names, @dhruv035 ? You can't call a field "bigint". It's "token ID", right ?

**Comment by dhruv035** [comment]
Minting Contract Address and tokenID, you can write something according to your understanding whatever seems fit, would be nice to have validation on these to make sure tx doesnt fail and pass this on to the args field, later we'll also have to add the option to fill n such forms in one go

**Comment by josealonso** [comment]
> Minting Contract Address and tokenID, would be nice to have validation on these to make sure tx doesnt fail and pass this on to the args field, later we'll also have to add the option to fill n such forms in one go

any validation library you recommend me ?

**Comment by dhruv035** [comment]
bigint and address are there types, for validation...

**Comment by josealonso** [comment]
@neatonk, correct me if I'm wrong. The only validation is the address having 22 characters: 0x plus the address itself. Can we validate something else ? EDIT: and start with `0x`

**Comment by neatonk** [comment]
The validation will be done in the contract to ensure that the provided NFT points to an audio file and that the NFT contract is an ERC721. This is not done and doesn't need to be done for the demo. See the notes under "each release must" on this issue: https://github.com/ReleaseClub/contracts/issues/1

**Comment by neatonk** [comment]
btw, I think this issue is done so I'm closing it. If you want to start thinking about how to do that contract in the validation that would be cool.

**Comment by josealonso** [comment]
> The validation will be done in the contract to ensure that the provided NFT points to an audio file and that the NFT contract is an ERC721. This is not done and doesn't need to be done for the demo. See the notes under "each release must" on this issue: [ReleaseClub/contracts#1](https://github.com/ReleaseClub/contracts/issues/1)

Thanks for the link. Although not completely needed, a basic validation on the frontend can be done.

**Comment by neatonk** [comment]
True enough, but we need the validation at the contract level for the UI to be forkable. Otherwise, someone could remove the validation in their own UI. Actually same is true without forking because people can change the UI in the browser to bypass validation.
