### ISSUE TITLE
Show spinner after form submit

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/release.club#41]
A spinner or other progress indicator is needed to provide user feedback when the form is submitted.

**Comment by josealonso** [comment]
The good thing about CSS frameworks like MUI or chakra-ui is that they have visual components and these tasks can be done quickly.

**Comment by neatonk** [comment]
Fair point @josealonso. Should be pretty quick with Tailwind as well though, just a different approach.

https://tailwindcss.com/docs/animation#spin
