### ISSUE TITLE
Choose a react component library

### ISSUE THREAD

**Issue by neatonk** [ReleaseClub/release.club#48]
A good component library should save us a lot of trouble and make it easier for new contributors to work with our code.

### Requirements (WIP/TBD)
- Strong focus on accessibility.
- Strong community and user base.
- Unopinionated and flexible.
- Excellent docs and DX.
- Typescript support.
- Made to be built on.
- Minimal build requirements.
- SSR support.
- ...

### Options:
- https://chakra-ui.com/
- https://www.radix-ui.com/
- https://degen-xyz.vercel.app/
- https://react-spectrum.adobe.com/react-aria/index.html
- ...

**Comment by salieflewis** [comment]
I've built with chakra before, but am interested in exploring mirror's design system as they are web3 native, and I'm curious what decisions they may have made to reflect that in their component library.

**Comment by josealonso** [comment]
As @salieflewis, I've built with **chakra-ui**. I like it. I've never heart of that *mirror* library you mention.

**Comment by neatonk** [comment]
Thanks @salieflewis and @josealonso for your feedback on the libs mentioned. I'd be happy to hear about any other component libs or design systems that you think would be a good fit. The requirements listed [above](https://github.com/ReleaseClub/release.club/issues/48#issue-1350289293) are off the top of my head and totally open for discussion, btw. Other than using react, the main constraint is that it should be convenient for others to fork, extend, and restyle our UI. 

Chakra has the advantage of being one of the most widely used react component systems, which means it will be familiar to most. That said, it's hard to know how widely used it is among developers likely to contribute to or fork our code. Notably, [thirdweb](https://github.com/thirdweb-dev/dashboard) uses chakra for their UI.

Degen is a fairly minimal design system created for [mirror.xyz](https://mirror.xyz). Notably, [catalog-factory](https://github.com/E-Rick/catalog-factory), [wagmi.sh](https://github.com/wagmi-dev/wagmi/tree/main/docs), and [ens.domains](https://github.com/ensdomains/thorin) all use or fork degen. That said, degen only makes sense if you plan to use it as is or fork it since the upstream repo does not accept contributions.

**Comment by josealonso** [comment]
> Thanks @salieflewis and @josealonso for your feedback on the libs mentioned. I'd be happy to hear about any other component libs or design systems that you think would be a good fit. The requirements listed [above](https://github.com/ReleaseClub/release.club/issues/48#issue-1350289293) are off the top of my head and totally open for discussion, btw. Other than using react, the main constraint is that it should be convenient for others to fork, extend, and restyle our UI.
> 
> Chakra has the advantage of being one of the most widely used react component systems, which means it will be familiar to most. That said, it's hard to know how widely used it is among developers likely to contribute to or fork our code. Notably, [thirdweb](https://github.com/thirdweb-dev/dashboard) uses chakra for their UI.
> 
> Degen is a fairly minimal design system created for [mirror.xyz](https://mirror.xyz). Notably, [catalog-factory](https://github.com/E-Rick/catalog-factory), [wagmi.sh](https://github.com/wagmi-dev/wagmi/tree/main/docs), and [ens.domains](https://github.com/ensdomains/thorin) all use or fork degen. That said, degen only makes sense if you plan to use it as is or fork it since the upstream repo does not accept contributions.

If *thirweb* uses **chakra-ui**, I would definitely choose that one. In my case, I had to use version 1 instead of version 2, because I didn't want to use React 18, due to the **hydration issues**.

**Comment by neatonk** [comment]
Our choice of component library has implications for the forkable club UI and components use cases described in https://github.com/ReleaseClub/release.club/issues/49.

> ## Use cases
>
> - A new project launches by extending our UI with additional content, custom theming and branding.
> - An existing project integrates our components and/or UI customized to match their existing theme.

I think chakra-ui would be a great fit for the first use case, especially because of it's familiarity and theme-ability. It would also be a good fit for existing projects built with chakra-ui. That said, I imagine it would not be a great fit for existing projects which do not use chakra—especially if the project has a mature design system using a different CSS-in-JS or static CSS solution.

To better support both use cases, we could choose a different component library (e.g. radix-ui primitives) or provide implementations for multiple component libraries (e.g. chakra and primitives). Another option would be to provide hooks that can be used in existing projects for which chakra does not make much sense.

Providing multiple implementations is the most flexible option with the best experience for all use cases, but with the highest maintenance burden. A layered implementation—with independent hooks, styles, and components—would reduce this burden. 

**My preference would be to start with a single component library and use a layered implementation to support additional component libraries in the future.**
